#
# PHP 5.6 installation, Debian/Ubuntu
#
# for Debian: Dotdeb Repository (http://www.dotdeb.org/)
# for Ubuntu: Ondrej Sury PPA (https://launchpad.net/~ondrej/+archive/ubuntu/php5-5.6)
#

- name: php - add repository key (Debian)
  apt_key:
    url: "http://www.dotdeb.org/dotdeb.gpg"
  when: ansible_distribution == "Debian"

- name: php - add repository (Debian)
  apt_repository:
    repo: "{{ item }}"
    state: "present"
    update_cache: yes
  with_items:
    - "deb http://packages.dotdeb.org {{ ansible_lsb.codename }} all"
    - "deb-src http://packages.dotdeb.org {{ ansible_lsb.codename }} all"
  when: ansible_distribution == "Debian"

- name: php - add repository (Ubuntu)
  apt_repository:
    repo: "ppa:ondrej/php"
    state: "present"
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: php - install packages
  apt:
    name: "{{ item }}"
    state: "present"
  with_items:
      - "php5-common"
      - "php5-cli"
      - "php5-fpm"
      - "php5-pgsql"
      - "php5-mysql"
      - "php5-gd"
      - "php5-json"
      - "php5-curl"
      - "php5-intl"
      - "php5-mcrypt"
      - "php5-memcached"
      - "php5-xdebug"
